name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libxrandr-dev \
          libxcursor-dev \
          libudev-dev \
          libopenal-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libxi-dev \
          libfreetype6-dev

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DBUILD_SHARED_LIBS=TRUE

    - name: Build
      run: cmake --build build --config Release
